/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    'category-groups': CategoryGroup;
    subcategories: Subcategory;
    'filter-groups': FilterGroup;
    'filter-options': FilterOption;
    products: Product;
    'product-reviews': ProductReview;
    coupons: Coupon;
    article: Article;
    orders: Order;
    'shipping-methods': ShippingMethod;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      productReviews: 'product-reviews';
    };
    coupons: {
      orders: 'orders';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'category-groups': CategoryGroupsSelect<false> | CategoryGroupsSelect<true>;
    subcategories: SubcategoriesSelect<false> | SubcategoriesSelect<true>;
    'filter-groups': FilterGroupsSelect<false> | FilterGroupsSelect<true>;
    'filter-options': FilterOptionsSelect<false> | FilterOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-reviews': ProductReviewsSelect<false> | ProductReviewsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    article: ArticleSelect<false> | ArticleSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'shipping-methods': ShippingMethodsSelect<false> | ShippingMethodsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'loyalty-settings': LoyaltySetting;
    'shipping-and-payment-page': ShippingAndPaymentPage;
    'returns-and-complaints-page': ReturnsAndComplaintsPage;
    'terms-and-conditions-page': TermsAndConditionsPage;
    'privacy-policy-page': PrivacyPolicyPage;
    'cookies-page': CookiesPage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'loyalty-settings': LoyaltySettingsSelect<false> | LoyaltySettingsSelect<true>;
    'shipping-and-payment-page': ShippingAndPaymentPageSelect<false> | ShippingAndPaymentPageSelect<true>;
    'returns-and-complaints-page': ReturnsAndComplaintsPageSelect<false> | ReturnsAndComplaintsPageSelect<true>;
    'terms-and-conditions-page': TermsAndConditionsPageSelect<false> | TermsAndConditionsPageSelect<true>;
    'privacy-policy-page': PrivacyPolicyPageSelect<false> | PrivacyPolicyPageSelect<true>;
    'cookies-page': CookiesPageSelect<false> | CookiesPageSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  displayName?: string | null;
  shippingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    country?: string | null;
    address?: string | null;
    city?: string | null;
    zip?: string | null;
  };
  billingAddress?: {
    firstName?: string | null;
    lastName?: string | null;
    phone?: string | null;
    country?: string | null;
    address?: string | null;
    city?: string | null;
    zip?: string | null;
    companyName?: string | null;
    companyId?: string | null;
    vatId?: string | null;
  };
  role: 'admin' | 'customer';
  bonusBalance?: number | null;
  earnedBonusTotal?: number | null;
  spentBonusTotal?: number | null;
  firstPurchaseDiscountUsed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Legacy visibility flag kept only for backward compatibility.
   */
  showInMenu?: boolean | null;
  /**
   * Display this category in the main header category menu on desktop.
   */
  showInDesktopMenu?: boolean | null;
  /**
   * Move this desktop-visible category out of the main header row and into the additional desktop dropdown menu.
   */
  showInDesktopDropdownMenu?: boolean | null;
  /**
   * Display this category in the mobile navigation menu.
   */
  showInMobileMenu?: boolean | null;
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Hide entire filter groups such as Material or Barva on this category level in the storefront.
   */
  hiddenFilterGroups?: (number | FilterGroup)[] | null;
  /**
   * Hide only specific filter options such as Cerná while keeping the rest of the filter visible.
   */
  hiddenFilterOptions?: (number | FilterOption)[] | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-groups".
 */
export interface FilterGroup {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-options".
 */
export interface FilterOption {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  group: number | FilterGroup;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category-groups".
 */
export interface CategoryGroup {
  id: number;
  name: string;
  /**
   * Generated from the parent category and group name to keep menu URLs unique.
   */
  slug: string;
  /**
   * Legacy visibility flag kept only for backward compatibility.
   */
  showInMenu?: boolean | null;
  /**
   * Display this group in the desktop header dropdown under its parent category.
   */
  showInDesktopMenu?: boolean | null;
  /**
   * Display this group in the mobile navigation menu.
   */
  showInMobileMenu?: boolean | null;
  sortOrder?: number | null;
  category: number | Category;
  description?: string | null;
  /**
   * Hide entire filter groups such as Material or Barva on this category level in the storefront.
   */
  hiddenFilterGroups?: (number | FilterGroup)[] | null;
  /**
   * Hide only specific filter options such as Cerná while keeping the rest of the filter visible.
   */
  hiddenFilterOptions?: (number | FilterOption)[] | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories".
 */
export interface Subcategory {
  id: number;
  name: string;
  /**
   * Generated from the parent group and subcategory name to keep storefront URLs unique.
   */
  slug: string;
  /**
   * Legacy visibility flag kept only for backward compatibility.
   */
  showInMenu?: boolean | null;
  /**
   * Display this subcategory in the desktop nested menu under its parent category group.
   */
  showInDesktopMenu?: boolean | null;
  /**
   * Display this subcategory in the mobile navigation menu.
   */
  showInMobileMenu?: boolean | null;
  sortOrder?: number | null;
  category: number | Category;
  categoryGroup: number | CategoryGroup;
  description?: string | null;
  /**
   * Hide entire filter groups such as Material or Barva on this category level in the storefront.
   */
  hiddenFilterGroups?: (number | FilterGroup)[] | null;
  /**
   * Hide only specific filter options such as Cerná while keeping the rest of the filter visible.
   */
  hiddenFilterOptions?: (number | FilterOption)[] | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  price: number;
  oldPrice?: number | null;
  sku?: string | null;
  stockQuantity?: number | null;
  /**
   * Used for popularity sorting on the storefront.
   */
  purchaseCount?: number | null;
  /**
   * Compact intro shown next to the product title.
   */
  shortDescription?: string | null;
  /**
   * Plain text used for summaries, fallbacks and feeds.
   */
  description?: string | null;
  /**
   * Fully editable content for the first "Popis" tab on the product page.
   */
  descriptionContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: number | Category;
  /**
   * Second navigation level used for grouped catalog menus and category landing pages.
   */
  categoryGroup?: (number | null) | CategoryGroup;
  subcategories?: (number | Subcategory)[] | null;
  mainImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Bullets shown under shipping/returns on the product page. Separate from the "Specifications / Další informace" tab.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  specifications?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  productReviews?: {
    docs?: (number | ProductReview)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Pick products that should appear in the color/variant block on the product page.
   */
  variantProducts?: (number | Product)[] | null;
  /**
   * Pick all filter options that apply to this product.
   */
  filterOptions?: (number | FilterOption)[] | null;
  status?: ('draft' | 'published') | null;
  isFeatured?: boolean | null;
  isRecommended?: boolean | null;
  /**
   * If set, displays "Do X dnů" on the storefront.
   */
  deliveryTime?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-reviews".
 */
export interface ProductReview {
  id: number;
  product: number | Product;
  user?: (number | null) | User;
  authorName: string;
  authorEmail: string;
  rating: number;
  /**
   * Publish this review on the product page.
   */
  show?: boolean | null;
  submittedAt?: string | null;
  comment: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  name: string;
  /**
   * Leave empty to auto-generate a random code.
   */
  code: string;
  discountPercent: number;
  /**
   * Use a full URL like https://lumerashop.cz/checkout or an internal path like /checkout. The coupon code is appended automatically.
   */
  websiteLink?: string | null;
  /**
   * Choose which coupon details should appear on the branded QR card preview.
   */
  qrCard?: {
    showTitle?: boolean | null;
    showDiscount?: boolean | null;
    showCode?: boolean | null;
    showSubtitle?: boolean | null;
    /**
     * Leave empty to use the coupon name automatically.
     */
    title?: string | null;
    subtitle?: string | null;
    note?: string | null;
  };
  isActive?: boolean | null;
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  previewSvg?: string | null;
  qrSvg?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderId: string;
  provider: 'stripe' | 'global-payments';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'canceled';
  user?: (number | null) | User;
  customerEmail: string;
  customerPhone?: string | null;
  customerFirstName?: string | null;
  customerLastName?: string | null;
  currency: string;
  subtotal: number;
  shippingTotal: number;
  total: number;
  discounts?: {
    coupon?: (number | null) | Coupon;
    couponCode?: string | null;
    couponDiscountPercent?: number | null;
    couponDiscountAmount?: number | null;
    firstPurchaseDiscountAmount?: number | null;
    bonusDiscountAmount?: number | null;
    discountedSubtotal?: number | null;
  };
  shippingAddress?: {
    country?: string | null;
    address?: string | null;
    city?: string | null;
    zip?: string | null;
    notes?: string | null;
  };
  billing?: {
    sameAsShipping?: boolean | null;
    isCompany?: boolean | null;
    firstName?: string | null;
    lastName?: string | null;
    address?: string | null;
    city?: string | null;
    zip?: string | null;
    country?: string | null;
    companyName?: string | null;
    companyId?: string | null;
    vatId?: string | null;
  };
  shipping?: {
    methodId?: string | null;
    label?: string | null;
    price?: number | null;
    pickupCarrier?: string | null;
    pickupPointId?: string | null;
    pickupPointCode?: string | null;
    pickupPointName?: string | null;
    pickupPointAddress?: string | null;
  };
  items?:
    | {
        product?: (number | null) | Product;
        productSnapshotId?: string | null;
        slug?: string | null;
        sku?: string | null;
        variant?: string | null;
        name: string;
        quantity: number;
        unitPrice: number;
        lineTotal: number;
        id?: string | null;
      }[]
    | null;
  pplShipment?: {
    batchId?: string | null;
    shipmentNumber?: string | null;
    importState?: string | null;
    labelFormat?: string | null;
    labelPageSize?: string | null;
    labelUrl?: string | null;
    completeLabelUrl?: string | null;
    generatedAt?: string | null;
    lastCheckedAt?: string | null;
    lastError?: string | null;
  };
  providerData?: {
    stripeSessionId?: string | null;
    stripePaymentIntentId?: string | null;
    globalTransactionId?: string | null;
    globalAuthCode?: string | null;
    lastEvent?: string | null;
    lastError?: string | null;
    providerResponse?: string | null;
  };
  loyalty?: {
    bonusUnitsSpent?: number | null;
    bonusUnitsEarned?: number | null;
  };
  zasilkovnaShipment?: {
    packetId?: string | null;
    packetNumber?: string | null;
    carrierNumber?: string | null;
    labelFormat?: string | null;
    labelMode?: string | null;
    generatedAt?: string | null;
    lastCheckedAt?: string | null;
    lastError?: string | null;
  };
  purchaseCountRecorded?: boolean | null;
  bonusLedgerRecorded?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article".
 */
export interface Article {
  id: number;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  title: string;
  mainImage: number | Media;
  description?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-methods".
 */
export interface ShippingMethod {
  id: number;
  methodId:
    | 'ppl-courier-cod'
    | 'ppl-pickup-cod'
    | 'ppl-courier'
    | 'ppl-pickup'
    | 'zasilkovna-courier'
    | 'zasilkovna-pickup'
    | 'personal-pickup';
  price: number;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'category-groups';
        value: number | CategoryGroup;
      } | null)
    | ({
        relationTo: 'subcategories';
        value: number | Subcategory;
      } | null)
    | ({
        relationTo: 'filter-groups';
        value: number | FilterGroup;
      } | null)
    | ({
        relationTo: 'filter-options';
        value: number | FilterOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-reviews';
        value: number | ProductReview;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'article';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'shipping-methods';
        value: number | ShippingMethod;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  displayName?: T;
  shippingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        phone?: T;
        country?: T;
        address?: T;
        city?: T;
        zip?: T;
      };
  billingAddress?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        phone?: T;
        country?: T;
        address?: T;
        city?: T;
        zip?: T;
        companyName?: T;
        companyId?: T;
        vatId?: T;
      };
  role?: T;
  bonusBalance?: T;
  earnedBonusTotal?: T;
  spentBonusTotal?: T;
  firstPurchaseDiscountUsed?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  showInMenu?: T;
  showInDesktopMenu?: T;
  showInDesktopDropdownMenu?: T;
  showInMobileMenu?: T;
  sortOrder?: T;
  description?: T;
  hiddenFilterGroups?: T;
  hiddenFilterOptions?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category-groups_select".
 */
export interface CategoryGroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  showInMenu?: T;
  showInDesktopMenu?: T;
  showInMobileMenu?: T;
  sortOrder?: T;
  category?: T;
  description?: T;
  hiddenFilterGroups?: T;
  hiddenFilterOptions?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories_select".
 */
export interface SubcategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  showInMenu?: T;
  showInDesktopMenu?: T;
  showInMobileMenu?: T;
  sortOrder?: T;
  category?: T;
  categoryGroup?: T;
  description?: T;
  hiddenFilterGroups?: T;
  hiddenFilterOptions?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-groups_select".
 */
export interface FilterGroupsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-options_select".
 */
export interface FilterOptionsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  group?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  price?: T;
  oldPrice?: T;
  sku?: T;
  stockQuantity?: T;
  purchaseCount?: T;
  shortDescription?: T;
  description?: T;
  descriptionContent?: T;
  category?: T;
  categoryGroup?: T;
  subcategories?: T;
  mainImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  productReviews?: T;
  variantProducts?: T;
  filterOptions?: T;
  status?: T;
  isFeatured?: T;
  isRecommended?: T;
  deliveryTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-reviews_select".
 */
export interface ProductReviewsSelect<T extends boolean = true> {
  product?: T;
  user?: T;
  authorName?: T;
  authorEmail?: T;
  rating?: T;
  show?: T;
  submittedAt?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  discountPercent?: T;
  websiteLink?: T;
  qrCard?:
    | T
    | {
        showTitle?: T;
        showDiscount?: T;
        showCode?: T;
        showSubtitle?: T;
        title?: T;
        subtitle?: T;
        note?: T;
      };
  isActive?: T;
  orders?: T;
  previewSvg?: T;
  qrSvg?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article_select".
 */
export interface ArticleSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  title?: T;
  mainImage?: T;
  description?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderId?: T;
  provider?: T;
  paymentStatus?: T;
  user?: T;
  customerEmail?: T;
  customerPhone?: T;
  customerFirstName?: T;
  customerLastName?: T;
  currency?: T;
  subtotal?: T;
  shippingTotal?: T;
  total?: T;
  discounts?:
    | T
    | {
        coupon?: T;
        couponCode?: T;
        couponDiscountPercent?: T;
        couponDiscountAmount?: T;
        firstPurchaseDiscountAmount?: T;
        bonusDiscountAmount?: T;
        discountedSubtotal?: T;
      };
  shippingAddress?:
    | T
    | {
        country?: T;
        address?: T;
        city?: T;
        zip?: T;
        notes?: T;
      };
  billing?:
    | T
    | {
        sameAsShipping?: T;
        isCompany?: T;
        firstName?: T;
        lastName?: T;
        address?: T;
        city?: T;
        zip?: T;
        country?: T;
        companyName?: T;
        companyId?: T;
        vatId?: T;
      };
  shipping?:
    | T
    | {
        methodId?: T;
        label?: T;
        price?: T;
        pickupCarrier?: T;
        pickupPointId?: T;
        pickupPointCode?: T;
        pickupPointName?: T;
        pickupPointAddress?: T;
      };
  items?:
    | T
    | {
        product?: T;
        productSnapshotId?: T;
        slug?: T;
        sku?: T;
        variant?: T;
        name?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  pplShipment?:
    | T
    | {
        batchId?: T;
        shipmentNumber?: T;
        importState?: T;
        labelFormat?: T;
        labelPageSize?: T;
        labelUrl?: T;
        completeLabelUrl?: T;
        generatedAt?: T;
        lastCheckedAt?: T;
        lastError?: T;
      };
  providerData?:
    | T
    | {
        stripeSessionId?: T;
        stripePaymentIntentId?: T;
        globalTransactionId?: T;
        globalAuthCode?: T;
        lastEvent?: T;
        lastError?: T;
        providerResponse?: T;
      };
  loyalty?:
    | T
    | {
        bonusUnitsSpent?: T;
        bonusUnitsEarned?: T;
      };
  zasilkovnaShipment?:
    | T
    | {
        packetId?: T;
        packetNumber?: T;
        carrierNumber?: T;
        labelFormat?: T;
        labelMode?: T;
        generatedAt?: T;
        lastCheckedAt?: T;
        lastError?: T;
      };
  purchaseCountRecorded?: T;
  bonusLedgerRecorded?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-methods_select".
 */
export interface ShippingMethodsSelect<T extends boolean = true> {
  methodId?: T;
  price?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  aboutSection: {
    title: string;
    description: string;
    buttonText: string;
    buttonLink: string;
  };
  marketingSlides?:
    | {
        title: string;
        description: string;
        button: string;
        link: string;
        bg: string;
        overlayImage: string;
        layout: {
          paddingTop: number;
          titleMaxWidth: number;
          descMaxWidth: number;
          img: {
            w: number;
            h: number;
            top: number;
            right: number;
          };
        };
        id?: string | null;
      }[]
    | null;
  testimonialsSection: {
    title: string;
    items?:
      | {
          text: string;
          author: string;
          location: string;
          id?: string | null;
        }[]
      | null;
  };
  blogSection?: {
    title?: string | null;
    description?: string | null;
    /**
     * Choose and order the articles for the homepage blog section. Leave empty to hide the block.
     */
    featuredArticles?: (number | Article)[] | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loyalty-settings".
 */
export interface LoyaltySetting {
  id: number;
  bonusesEnabled?: boolean | null;
  earningRule: {
    /**
     * For every X CZK paid for products, award bonus units.
     */
    spendAmount: number;
    bonusUnits: number;
  };
  redemptionRule: {
    bonusUnits: number;
    /**
     * How much money the selected bonus block removes from product subtotal.
     */
    discountAmount: number;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-and-payment-page".
 */
export interface ShippingAndPaymentPage {
  id: number;
  title: string;
  /**
   * Image shown in the large hero banner above the page content.
   */
  heroImage?: (number | null) | Media;
  /**
   * This page is rendered on the storefront footer route and uses the Lexical editor.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns-and-complaints-page".
 */
export interface ReturnsAndComplaintsPage {
  id: number;
  title: string;
  /**
   * Image shown in the large hero banner above the page content.
   */
  heroImage?: (number | null) | Media;
  /**
   * This page is rendered on the storefront footer route and uses the Lexical editor.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions-page".
 */
export interface TermsAndConditionsPage {
  id: number;
  title: string;
  /**
   * Image shown in the large hero banner above the page content.
   */
  heroImage?: (number | null) | Media;
  /**
   * This page is rendered on the storefront footer route and uses the Lexical editor.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy-page".
 */
export interface PrivacyPolicyPage {
  id: number;
  title: string;
  /**
   * Image shown in the large hero banner above the page content.
   */
  heroImage?: (number | null) | Media;
  /**
   * This page is rendered on the storefront footer route and uses the Lexical editor.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookies-page".
 */
export interface CookiesPage {
  id: number;
  title: string;
  /**
   * Image shown in the large hero banner above the page content.
   */
  heroImage?: (number | null) | Media;
  /**
   * This page is rendered on the storefront footer route and uses the Lexical editor.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  aboutSection?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  marketingSlides?:
    | T
    | {
        title?: T;
        description?: T;
        button?: T;
        link?: T;
        bg?: T;
        overlayImage?: T;
        layout?:
          | T
          | {
              paddingTop?: T;
              titleMaxWidth?: T;
              descMaxWidth?: T;
              img?:
                | T
                | {
                    w?: T;
                    h?: T;
                    top?: T;
                    right?: T;
                  };
            };
        id?: T;
      };
  testimonialsSection?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              text?: T;
              author?: T;
              location?: T;
              id?: T;
            };
      };
  blogSection?:
    | T
    | {
        title?: T;
        description?: T;
        featuredArticles?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loyalty-settings_select".
 */
export interface LoyaltySettingsSelect<T extends boolean = true> {
  bonusesEnabled?: T;
  earningRule?:
    | T
    | {
        spendAmount?: T;
        bonusUnits?: T;
      };
  redemptionRule?:
    | T
    | {
        bonusUnits?: T;
        discountAmount?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-and-payment-page_select".
 */
export interface ShippingAndPaymentPageSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns-and-complaints-page_select".
 */
export interface ReturnsAndComplaintsPageSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions-page_select".
 */
export interface TermsAndConditionsPageSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy-page_select".
 */
export interface PrivacyPolicyPageSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookies-page_select".
 */
export interface CookiesPageSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}